--CONSULTANDO TODA LA INFORMACION DE LA TABLA CUSTOMERS
SELECT * FROM Customers

--CONSULTANDO LA INFORMACION DE LA TABLA CUSTOMERS DONDE EL CustomerID='ALFKI'
SELECT * FROM Customers WHERE CustomerID='ALFKI'

--ACTUALIZAR EL PAIS DEL CUSTOMERID ALFKI
UPDATE Customers
SET Country='France'
WHERE CustomerID = 'ALFKI'

--OBTENIENDO EL CUSTOMERID
SELECT CUSTOMERID FROM Customers
WHERE Country='France' and ContactName='Maria Anders'

--ACTUALIZAR PAIS FRANCE A FRANCIA DEL CUSTOMERID ALFKI
UPDATE Customers
SET Country='Francia'
WHERE CustomerID = ?