--UTILIZANDO LA BASE DE DATOS STREAMING
USE STREAMING
GO

--CREANDO LA TABLA VENTAS VIDEO JUEGO
CREATE TABLE VideoJuegos(
Cod_Archivo VARCHAR(20),
Nombres VARCHAR(100),
Año VARCHAR(4),
Edad VARCHAR(2),
Plataforma VARCHAR(50),
Juego VARCHAR(max)
)
go

--CONTANDO LA CANTIDAD DE REGISTRO DE LA TABLA VideoJuegos
SELECT COUNT(*) FROM VideoJuegos
go

--SELECCIONANDO TODAS LAS COLUMNAS DE LA TABLA VideoJuegos
SELECT * FROM VideoJuegos
GO

--SELECCIONANDO LOS DISTINTOS CODIGOS DE LA TABLA VideoJuegos
SELECT DISTINCT COD_ARCHIVO FROM VideoJuegos
GO

--CONTANDO LA CANTIDAD DE REGISTRO AGRUPADO POR EL Cod_Archivo DE LA TABLA VideoJuegos
SELECT Cod_Archivo, count(*) as Cantidad from VideoJuegos
group by Cod_Archivo
go