--CACHE TRANSFORM

--USAR LA BASE [STREAMING]
USE STREAMING
GO

--VALIDANDO SI EXISTE LA TABLA Busqueda
IF EXISTS(SELECT NAME FROM SYS.tables WHERE NAME='Busqueda')
BEGIN
	DROP TABLE Busqueda
END
GO

--CREANDO LA TABLA BUSQUEDA
CREATE TABLE Busqueda(
CodigoRegion NVARCHAR(50),
NombreRegion NVARCHAR(50)
)
GO

SELECT * FROM Busqueda
GO